// AUTO-GENERATED by scripts/apply-project-updates.mjs — do not edit by hand.

class BrandConfig {
  BrandConfig._();

  static const String name = 'AMMARS FRESH';
  static const String nameAr = 'أمارز فرش';
  static const String legalName = 'AMMARS FRESH';
  static const String tagline = 'Digital data-driven B2B agri-tech platform';
  static const String taglineAr = 'منصة زراعية رقمية مدعومة بالبيانات للأعمال بين الشركات';
  static const String country = 'South Sudan';
  static const String city = 'Juba';
  static const String mission = 'To solve the post-harvest and other losses that farmers face in South Sudan by digitalizing the supply chain.';
  static const List<String> currencies = ['USD', 'SSP', 'USG'];
  static const String currenciesInline = 'USD/SSP/USG';
  static const String defaultCurrency = 'SSP';
  static const String supportEmail = 'hello@ammarsfresh.ss';
  static const String website = 'www.ammarsfresh.ss';
}
